#!/usr/bin/env bash

# initial deps
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# linking
pushd ~ > /dev/null

default_dir="$(pwd)/dotfiles"

echo "using $default_dir as target dir"

dir=${1:-$default_dir}

base_files=(
".zexports"
".zprofile"
".zshenv"
".zshrc"
)

config_files=(
"nvim"
"tmux"
"wezterm"
)

echo "~: linking started"
for i in "${base_files[@]}"; do
	ln -svfT "$dir/$i" "$i" || exit
done
echo "~: linking done"

echo ".config: linking started"
mkdir -p .config && pushd .config > /dev/null || exit
for j in "${config_files[@]}"; do
	ln -svfT "$dir/$j" "$j" || exit
done
popd > /dev/null
echo ".config: linking done"


popd > /dev/null
